# Generated by Django 4.2.5 on 2023-09-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("subject", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=4000)),
                ("regdate", models.DateTimeField(auto_now_add=True)),
                ("readcnt", models.IntegerField(default=0)),
                ("file1", models.CharField(max_length=300)),
            ],
        ),
    ]
